apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homectl-auth
  namespace: homectl
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - auth.homectl.no
      secretName: homectl-auth-tls
  rules:
    - host: auth.homectl.no
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homectl-auth
                port:
                  name: http
